services:
  fossflow:
    build: .
    ports:
      - "3000:80"
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - ENABLE_SERVER_STORAGE=true
      - STORAGE_PATH=/data/diagrams
      - ENABLE_GIT_BACKUP=false
      - JWT_SECRET=supersecretkey
      - REFRESH_SECRET=superrefreshsecret
      - ROOT_USERNAME=root
      - ROOT_PASSWORD=Password1236
      - ADMIN_USER=root
      - ADMIN_PASS=Password1236
    volumes:
      - ./diagrams:/data/diagrams